apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantcatalog-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantcatalogservice
  template:
    metadata:
      labels:
        app: restaurantcatalogservice
    spec:
      containers:
        - name: restaurantcatalogservice
          image: juicl/restaurantcatalogservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantcatalog-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: restaurantcatalogservice
  ports:
  - name: restaurantcatalogservice
    protocol: TCP
    port: 80
    targetPort: 80