version: '3.4'
services:
  fooddelivery.restaurantcatalogapi:
    image: ${DOCKER_REGISTRY-}fooddeliveryrestaurantcatalogapi
    container_name: restaurantcatalog.api
    build:
      context: .
      dockerfile: FoodDelivery.RestaurantCatalogApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  restaurantcatalog.database:
    image: postgres
    container_name: restaurantcatalog.database
    environment:
      - POSTGRES_DB=restaurantApi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - "5434:5432"
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data
        
  
volumes:
  pgdata: